#log
logging:
  config: classpath:logback.xml
  level:
    com:
      cf: debug

#server
server:
  port: 9999
  servlet-path: /taurus-base
  tomcat:
    basedir: .
    accesslog:
      enabled: true
      directory: ./logs
      pattern: "%{X-Forwarded-For}i %a %{X-B3-TraceId}i %t %m %U %s %b %D"
      rename-on-rotate: true
      suffix: .log
      prefix: access
      rotate: true
      buffered: false
      file-date-format: yyyy-MM-dd

#admin
management:
  security:
    enabled: false

#graceful quit
endpoints:
  shutdown:
    enabled: true
    sensitive: false

spring:
  application:
    name: taurus-base

#database
data-base-router:
  enabled: true
  single:
    - alias: main
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://47.97.163.100:3306/taurus?useUnicode=true&characterEncoding=utf8&useSSL=true
      username: root
      password: password
      type: com.alibaba.druid.pool.DruidDataSource
      filters: stat
      maxActive: 20
      initialSize: 1
      maxWait: 60000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 'x'
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20

mybatis:
  mapper-locations: classpath:com/cf/taurus/base/dao/*.xml
  type-aliases-package: com.cf.taurus.common.po
  config-location: classpath:mybatis-config.xml
